#!/bin/bash

# Default library location
if [ -z "$BACONBITS_LIBS" ]
then
	BACONBITS_LIB="/usr/share/baconbits/lib"
fi

# If this doesn't exist, BaconBits hasn't been installed so load local libs
if [ ! -d $BACONBITS_LIB ]
then
	BACONBITS_LIB="lib"
	libs=$BACONBITS_LIB/* # Get all the libraries
	. lib/loader          # Load the loader library
	bb_loader $libs       # Dynamically load all libraries
# BaconBits has been installed
else
	libs=$BACONBITS_LIB/lib/* # Get all the labraries
	. $BACONBITS_LIB/loader   # Load the loader library
	bb_loader $libs           # Dynamically load all the libraries
fi

##
#
# Main controller for BaconBits options
#
##
function main {
	# No args, show help
	if [ $# -lt 1 ]
	then
		bb_help
	fi

	# Parse first option and look for where to route it
	case $1 in
		c*)
			shift
			bb_clean $@
		;;
		h*)
			shift
			bb_help $@
		;;
		ini*)
			shift
			bb_init $@
		;;
		ins*)
			shift
			bb_install $@
		;;
		s*)
			shift
			bb_show $@
		;;
		un*)
			shift
			bb_uninstall $@
		;;
		up*)
			shift
			bb_update $@
		;;
		us*)
			shift
			bb_use $@
		;;
		*)
			echo "ERROR: unrecognized options: '$@'. Try: $0 help"
			exit 1
		;;
	esac

	exit 0
}

# Let it begin
main $@

# EOF
