#!/bin/bash

#
# Dynamically loads BaconBits libraries
#
function bb_loader {
	warn=0 # Default to a clean return with no warnings

	# Load all the libraries requested
	for lib in $@
	do
		tmp=$(basename $lib) # Just the file name

		# Don't double load ourself
		if [ $tmp == "loader" ]
		then
			continue
		fi

		# If the library exists, load it
		if [ -f $lib ]
		then
			. $lib
		else
			echo "WARNING: Unknown library '$lib'" > /dev/stderr
			warn=1
		fi
	done

	return $warn
}

# EOF
